

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UsersManager.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class UsersDBEntities : DbContext
{
    public UsersDBEntities()
        : base("name=UsersDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        // This cause problems with Azure
        // throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Gender> Genders { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserType> UserTypes { get; set; }

    public virtual DbSet<UnverifiedEmail> UnverifiedEmails { get; set; }

    public virtual DbSet<ResetPasswordCommand> ResetPasswordCommands { get; set; }

    public virtual DbSet<Login> Logins { get; set; }

    public virtual DbSet<FriendShip> FriendShips { get; set; }

    public virtual DbSet<Photo> Photos { get; set; }

    public virtual DbSet<PhotoVisibility> PhotoVisibilities { get; set; }

    public virtual DbSet<PhotoRating> PhotoRatings { get; set; }

}

}

